// Mocks generated by Mockito 5.3.2 from annotations
// in flutter_expense_tracker/test/transaction/controllers/transaction_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter/material.dart' as _i3;
import 'package:flutter_expense_tracker/utils/bottom_sheet/bottom_sheet_controller.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BottomSheetController].
///
/// See the documentation for Mockito's code generation for more information.
class MockBottomSheetController extends _i1.Mock
    implements _i2.BottomSheetController {
  @override
  void closeBottomSheet(_i3.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #closeBottomSheet,
          [context],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void showBaseBottomSheet(
    _i3.BuildContext? context,
    _i3.Widget? child,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #showBaseBottomSheet,
          [
            context,
            child,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
